services:
  - type: web
    name: esp32-monitor-server
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: esp32-monitor-db
          property: connectionString

databases:
  - name: esp32-monitor-db
    plan: free
    databaseName: esp32_monitor
    user: esp32_user